config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'homes#top'
  get "" => 'homes#top'
  get "homes/about" => "homes#about", as: "about"
  resources :books_image
  resources :users, only: [:show, :edit, :create, :index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    users_show_path
  end
  
  def after_sign_out_path_for(resource)
    top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/models/book_image.rb
class Book < ApplicationRecord
  has_one_attached :image  
  belongs_to :user
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :book_images, dependent: :destroy
  
  has_one_attached :book_image
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_images_path
  end
  
  def after_sign_out_path_for(resource)
    top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
  end
  
  # 投稿データの保存
  def create
    @book_image = BookImage.new(book_image_params)
    @book_image.user_id = current_user.id
    if @book_image.save
    redirect_to book_images_path
    else
      @books = Book.all
      render :index
    end
  end

  def edit
  end


  def destroy
  end

  def update
  end
  
  # 投稿データのストロングパラメータ
  private

  def book_image_params
    params.require(:book_image).permit(:book_name, :image, :caption)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book_images  = @user.book_images    
  end

  def edit
    @user = User.find(params[:id])
  end
  
  # 投稿データの保存
  def create
    @user = BookImage.new(book_image_params)
    @user.book_id = current_user.id  
    @user.save
    redirect_to user_path
  end
  
  #データの再新と再新結果の表示先
  def update
    user = User.find(params[:id]) #ユーザーの取得
    user.update(user_params) #ユーザーのアップデート
    redirect_to user_path(user.id)  #ユーザーの詳細ページへのパス
  end

  def index
    @users = User.all
    @user = User.new
  end
  
  # 投稿データのストロングパラメータ
  private

  def user_params
    params.require(:user).permit(:name, :book_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div class="card-list-container py-5">
  <% book_images.each do |book_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to book_image_path(book_image.id) do %>
      <%= image_tag book_image.get_image, class: "card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag book_image.user.get_profile_image(100,100), class: "mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(book_image_path(book_image.id), class: "text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= book_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= book_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= book_image.user.name %> ｜ </span>
          <span><%= link_to "#{book_image.book_comments.count} コメント", book_image_path(book_image.id), class: "text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate book_images %>
</div>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/top.html.erb
<main>
  <p id = "notice">Signed out successfully.</p>
  <div class="container">
  <div class="row">
    <h1>welcome to Bookers ‼</h1>
    <p>In  Bookers </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a href="/users/sign_in" class="btn btn-info btn-sm btn-block mb-3 sign_in">Log in</a>
        </div>
        <div class="row">
          <a href="/users/sign_up" class="btn btn-success btn-sm btn-block sign_up">Sign up</a>
        </div>
      </div>
     <p>CopyRight Infratop.inc</p>
  </div
  </div>
</main>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/<script src="https://kit.fontawesome.com/97939798b7.js" crossorigin="anonymous"></script>.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to "Log aut, destroy_book_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li>
              <%= link_to 'Books', index_book_image_path(current_book.id), class: 'nav-link text-dark' %>
            </li>
            <li>
              <%= link_to 'Users', index_user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li>
              <%= link_to "Home", home_top_path %>
            </li>
            
            <% else %>
            <li>
              <%= link_to "Sign in", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "About", home_top_path %>
            </li>
            <li>
              <%= link_to "Home", home_top_path %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model: @users_image do |f| %>

  <h4>image</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>Introduction</h4>
  <%= f.text_area :caption %>

  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<h1>Users#top</h1>
<p>Find me in app/views/users/top.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>